### ISSUE TITLE
[오자수정] README.md

### ISSUE THREAD

**Issue by eyabc** [next-step/js-todo-list-step3#18]
![image](https://user-images.githubusercontent.com/31977543/95905443-d18ef680-0dd3-11eb-8e1f-ef052ab7e6a6.png)

itemId 를 teamId 로 변경하는게 어울릴 것 같습니다

**Comment by ganeodolu** [comment]
@eyabc 님 오타 제보 감사드립니다. 수정하였습니다. 🤗

**Comment by imakerjun** [comment]
@eyabc 은영님 오타 제보 감사드립니다! 👍🏻
